const data=raw.split('\n').map((x,id)=>{const[name,club,league,area]=x.split('|');
return{id:String(id),name,clubs:club.split('／'),leagues:league.split('／'),area}}),teamLeague={};
data.forEach(s=>s.clubs.forEach((t,i)=>teamLeague[t]=s.leagues[i]||s.leagues[0]));
const teams=[...new Set(data.flatMap(s=>s.clubs))],teamOrder=Object.fromEntries(teams.map((t,i)=>[t,i]));
let visited=[],visitedTeams=[];
try{visited=JSON.parse(localStorage.getItem('j-stadium-visited')||'[]');
visitedTeams=JSON.parse(localStorage.getItem('j-team-visited')||'[]')}catch{}let league='ALL';
const $=id=>document.getElementById(id),save=()=>{localStorage.setItem('j-stadium-visited',JSON.stringify(visited));
localStorage.setItem('j-team-visited',JSON.stringify(visitedTeams))};
function render(){const q=$('q').value.toLowerCase(),only=$('only').checked,scope=data.filter(s=>league==='ALL'||s.leagues.includes(league)),scopeTeams=league==='ALL'?teams:[...new Set(scope.flatMap(s=>s.clubs).filter(t=>teamLeague[t]===league))],scopeVisited=scope.filter(s=>visited.includes(s.id)),scopeVisitedTeams=scopeTeams.filter(t=>visitedTeams.includes(t)),shown=scope.filter(s=>(!only||!visited.includes(s.id))&&(s.name+s.clubs.join('')+s.area).toLowerCase().includes(q)).sort((a,b)=>Math.min(...a.clubs.map(t=>teamOrder[t]))-Math.min(...b.clubs.map(t=>teamOrder[t]))||Number(a.id)-Number(b.id)),pct=Math.round(scopeVisited.length/scope.length*100),tp=Math.round(scopeVisitedTeams.length/scopeTeams.length*100);
$('done').textContent=scopeVisited.length;
$('total').textContent=scope.length;
$('pct').textContent=pct+'%';
$('bar').style.width=pct+'%';
$('teamDone').textContent=scopeVisitedTeams.length;
$('teamTotal').textContent=scopeTeams.length;
$('teamPct').textContent=tp+'%';
$('teamBar').style.width=tp+'%';
$('count').textContent=shown.length+'件';
$('items').innerHTML=shown.map(s=>`<div class="stadium ${visited.includes(s.id)?'done':''}"><div class="stadium-main"><button class="visit" data-id="${s.id}" aria-label="${s.name}へ行った">${visited.includes(s.id)?'✓':''}</button><span class="info"><span class="name">${s.name}</span><span class="area">${s.area}</span></span><span class="badge ${league==='ALL'?s.leagues[0]:league}">${league==='ALL'?s.leagues.join('・'):league}</span></div><div class="teams"><span class="teams-label">行ったチーム</span>${s.clubs.filter(t=>league==='ALL'||teamLeague[t]===league).map(t=>`<button class="team ${visitedTeams.includes(t)?'done':''}" data-team="${t}">${visitedTeams.includes(t)?'✓ ':''}${t}</button>`).join('')}</div></div>`).join('');
document.querySelectorAll('.visit').forEach(b=>b.onclick=()=>{const id=b.dataset.id;
visited=visited.includes(id)?visited.filter(x=>x!==id):[...visited,id];
save();
render()});
document.querySelectorAll('.team').forEach(b=>b.onclick=()=>{const t=b.dataset.team;
visitedTeams=visitedTeams.includes(t)?visitedTeams.filter(x=>x!==t):[...visitedTeams,t];
save();
render()})}document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{league=b.dataset.l;
document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('active',x===b));
render()});
$('q').oninput=render;
$('only').onchange=render;
render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
