let sharedDb=null,isAdmin=false;
const sharedDoc=()=>sharedDb.collection('public').doc('jleague-stadium-log');
function firebaseConfigured(){const c=window.FIREBASE_CONFIG||{};return c.apiKey&&!String(c.apiKey).includes('ここに')&&c.projectId&&!String(c.projectId).includes('ここに')}
async function setMode(user){isAdmin=!!user;document.body.classList.toggle('viewer-mode',!isAdmin);$('loginBtn').hidden=isAdmin;$('logoutBtn').hidden=!isAdmin;$('modeStatus').textContent=isAdmin?'管理者モード：編集できます':'閲覧モード：記録の変更はできません';render();if(isAdmin&&sharedDb){const s=await sharedDoc().get();if(!s.exists)await saveShared()}}
function ensureModeUI(){document.body.classList.add('viewer-mode');document.querySelector('footer').textContent='家族はログイン不要で閲覧できます。記録の変更には管理者ログインが必要です';const panel=document.createElement('div');panel.className='mode-panel';panel.innerHTML='<span class="mode-status" id="modeStatus">閲覧モード</span><button class="mode-button" id="loginBtn">管理者ログイン</button><button class="mode-button logout" id="logoutBtn" hidden>ログアウト</button>';document.querySelector('header .top').after(panel);const overlay=document.createElement('div');overlay.className='login-overlay';overlay.id='loginOverlay';overlay.innerHTML='<div class="login-card"><h2>管理者ログイン</h2><p>記録を変更する場合だけログインしてください</p><label for="adminEmail">メールアドレス</label><input id="adminEmail" type="email" autocomplete="username"><label for="adminPassword">パスワード</label><input id="adminPassword" type="password" autocomplete="current-password"><p class="login-error" id="loginError"></p><div class="login-actions"><button class="login-cancel" id="loginCancel">キャンセル</button><button class="login-submit" id="loginSubmit">ログイン</button></div></div>';document.body.append(overlay);$('loginBtn').onclick=openLogin;$('logoutBtn').onclick=logoutAdmin;$('loginCancel').onclick=closeLogin;$('loginSubmit').onclick=loginAdmin;$('loginOverlay').onclick=e=>{if(e.target===$('loginOverlay'))closeLogin()};$('adminPassword').onkeydown=e=>{if(e.key==='Enter')loginAdmin()}}
function initShared(){ensureModeUI();if(!firebaseConfigured()){$('modeStatus').textContent='閲覧モード（Firebase設定が必要です）';$('loginBtn').disabled=true;render();return}try{firebase.initializeApp(window.FIREBASE_CONFIG);sharedDb=firebase.firestore();firebase.auth().onAuthStateChanged(setMode);sharedDoc().onSnapshot(s=>{if(s.exists){const d=s.data();visited=Array.isArray(d.visited)?d.visited:[];visitedTeams=Array.isArray(d.visitedTeams)?d.visitedTeams:[];localStorage.setItem('j-stadium-visited',JSON.stringify(visited));localStorage.setItem('j-team-visited',JSON.stringify(visitedTeams));render()}},()=>{$('modeStatus').textContent='共有データを読み込めませんでした'})}catch(e){$('modeStatus').textContent='Firebase設定を確認してください';$('loginBtn').disabled=true}}
async function saveShared(){localStorage.setItem('j-stadium-visited',JSON.stringify(visited));localStorage.setItem('j-team-visited',JSON.stringify(visitedTeams));if(isAdmin&&sharedDb)await sharedDoc().set({visited,visitedTeams,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}
function openLogin(){$('loginError').textContent='';$('loginOverlay').classList.add('open');$('adminEmail').focus()}
function closeLogin(){$('loginOverlay').classList.remove('open');$('adminPassword').value=''}
async function loginAdmin(){$('loginError').textContent='';$('loginSubmit').disabled=true;try{await firebase.auth().signInWithEmailAndPassword($('adminEmail').value.trim(),$('adminPassword').value);closeLogin()}catch(e){$('loginError').textContent='メールアドレスまたはパスワードが正しくありません'}finally{$('loginSubmit').disabled=false}}
async function logoutAdmin(){await firebase.auth().signOut()}
